// apps/oshonz-website/src/app/EventList.tsx
'use client';

import { DateTime } from 'luxon';
import { FC, useState } from 'react';

import { Button, Modal, Panel } from 'apps-web';

import { getInstructionUrl, getShortAddress } from '../common/data';
import { Event } from '../common/types';

type Props =
{
  events: Event[];
};

const EventList: FC<Props> = ({ events }) =>
{
  const [ event, setEvent ] = useState<Event>();

  const description = event?.description
    .replace('CANCELLED', '')
    .trim()
    .replace(/\n/g, '<br>');

  return (
    <>
      <div className="o-column">
        {!events.length && 'Oops! There\'s nothing here yet. Please check again later or join the mailing list (below) to get notified.'}
        {events.map(event =>
          <Panel
            key={event.id}
            shade="front"
            className="o-column u-rounded u-p"
          >
            <div>
              <h3 className="o-column">
                {event.description.includes('CANCELLED') &&
                  <div className="u-color--danger">Sorry this meditation has been CANCELLED</div>
                }
                {event.summary}
              </h3>
              <div>{getShortAddress(event.address)}</div>
              <div>{DateTime.fromISO(event.start).toFormat('EEEE, MMMM d @ h:mm a')}</div>
            </div>
            <div>
              <Button shade="front" onClick={() => setEvent(event)}>Learn more</Button>
            </div>
          </Panel>
        )}
      </div>

      {event &&
        <Modal
          className="o-column u-rounded u-p"
          onDismiss={() => setEvent(undefined)}
        >
          <h3 className="o-column">
            {event.description.includes('CANCELLED') &&
              <div className="u-color--danger">Sorry this meditation has been CANCELLED</div>
            }
            {event.summary}
          </h3>
          <div>{getShortAddress(event.address)} (<a href={ `https://www.google.com/maps?q=${encodeURIComponent(event.address)}` } target="_blank" rel="noreferrer">open map</a>)</div>
          <div>{DateTime.fromISO(event.start).toFormat('EEEE, MMMM d @ h:mm a')}</div>
          {getInstructionUrl(event.summary) &&
            <a href={getInstructionUrl(event.summary)} target="_blank" rel="noreferrer">
              Read the full instructions here
            </a>
          }
          {description && <div dangerouslySetInnerHTML={{ __html: description }} />}
        </Modal>
      }
    </>
  );
};

export default EventList;

// apps/oshonz-website/src/web-components/event-list.ts
import { DateTime } from 'luxon';

import { getInstructionUrl, getShortAddress } from '../common/data';
import { Event } from '../common/types';

class OSHOEventList extends HTMLElement
{
  events?: Event[] = undefined;

  async connectedCallback()
  {
    if (!this.events) return;

    const eventTemplate = document.querySelector('.c-event__template') as HTMLTemplateElement;

    for (const event of this.events)
    {
      const eventContainer = eventTemplate.content.cloneNode(true) as HTMLElement;

      const eventTitle = eventContainer.querySelector('.c-event__title') as HTMLElement;
      eventTitle.appendChild(document.createTextNode(event.summary));

      if (event.description.includes('CANCELLED'))
      {
        const cancelled = document.createElement('div');
        cancelled.className = 'u-danger';
        cancelled.innerText = 'Sorry this meditation has been CANCELLED';
        eventTitle.appendChild(cancelled);
      }

      const eventAddress = eventContainer.querySelector('.c-event__address') as HTMLElement;
      eventAddress.innerText = getShortAddress(event.address) ?? '';

      const eventTime = eventContainer.querySelector('.c-event__time') as HTMLElement;
      eventTime.innerText = DateTime.fromISO(event.start).toFormat('EEEE, MMMM d @ h:mm a');

      const eventOpen = eventContainer.querySelector('.c-event__open') as HTMLElement;
      eventOpen.onclick = () => this.openEvent(event);

      this.appendChild(eventContainer);
    }
  }

  openEvent(event: Event)
  {
    const eventDialogTemplate = document.querySelector('.c-event-dialog__template') as HTMLTemplateElement;
    const eventDialogContainer = eventDialogTemplate.content.cloneNode(true) as HTMLElement;

    const eventBody = eventDialogContainer.querySelector('.c-event-dialog__body') as HTMLElement;

    const eventTitle = eventDialogContainer.querySelector('.c-event-dialog__title') as HTMLElement;
    eventTitle.appendChild(document.createTextNode(event.summary));

    if (event.description.includes('CANCELLED'))
    {
      const cancelled = document.createElement('div');
      cancelled.className = 'u-danger';
      cancelled.innerText = 'Sorry this meditation has been CANCELLED';
      eventTitle.appendChild(cancelled);
    }

    const eventAddress = eventDialogContainer.querySelector('.c-event-dialog__address') as HTMLElement;
    eventAddress.appendChild(document.createTextNode(`${getShortAddress(event.address)} (`));

    const eventAddressLink = document.createElement('a', { is: 'basis-a' });
    eventAddressLink.href = `https://www.google.com/maps?q=${encodeURIComponent(event.address)}`;
    eventAddressLink.innerText = 'open map';
    eventAddress.appendChild(eventAddressLink);

    eventAddress.appendChild(document.createTextNode(')'));

    const eventTime = eventDialogContainer.querySelector('.c-event-dialog__time') as HTMLElement;
    eventTime.innerText = DateTime.fromISO(event.start).toFormat('EEEE, MMMM d @ h:mm a');

    const instructionsUrl = getInstructionUrl(event.summary);
    if (instructionsUrl)
    {
      const eventInstructionsLink = document.createElement('a', { is: 'basis-a' });
      eventInstructionsLink.href = `https://www.google.com/maps?q=${encodeURIComponent(event.address)}`;
      eventInstructionsLink.innerText = 'Read the full instructions here';
      eventBody.appendChild(eventInstructionsLink);
    }

    if (event.description)
    {
      const description = event.description
        .replace('CANCELLED', '')
        .trim()
        .replace(/\n/g, '<br>');

      const eventDescription = document.createElement('div');
      eventDescription.innerText = description;
      eventBody.appendChild(eventDescription);
    }

    const eventDialog = document.querySelector('.c-event-dialog') as HTMLDialogElement;
    const lastEventDialogChild = eventDialog.lastElementChild;
    if (lastEventDialogChild?.classList.contains('c-event-dialog__body'))
    {
      lastEventDialogChild.remove();
    }
    eventDialog.appendChild(eventDialogContainer);
    eventDialog.showModal();
  }
}

customElements.define('osho-event-list', OSHOEventList);

export default OSHOEventList;
